// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// Tweet defines model for Tweet.
type Tweet struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	Text      string    `json:"text"`
}

// TweetCreate defines model for TweetCreate.
type TweetCreate struct {
	Text string `json:"text"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"accessToken"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error string `json:"error"`
}

// InternalError defines model for InternalError.
type InternalError struct {
	Error string `json:"error"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Error string `json:"error"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateTweetJSONRequestBody defines body for CreateTweet for application/json ContentType.
type CreateTweetJSONRequestBody = TweetCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вход
	// (POST /api/1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Выход
	// (POST /api/1/auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Регистрация нового пользователя
	// (POST /api/1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Создать новый пост
	// (POST /api/1/tweets/create_post)
	CreateTweet(w http.ResponseWriter, r *http.Request)
	// Получить ленту постов
	// (GET /api/1/tweets/feed)
	GetFeed(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Вход
// (POST /api/1/auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Выход
// (POST /api/1/auth/logout)
func (_ Unimplemented) LogoutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация нового пользователя
// (POST /api/1/auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новый пост
// (POST /api/1/tweets/create_post)
func (_ Unimplemented) CreateTweet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить ленту постов
// (GET /api/1/tweets/feed)
func (_ Unimplemented) GetFeed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTweet operation middleware
func (siw *ServerInterfaceWrapper) CreateTweet(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTweet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFeed operation middleware
func (siw *ServerInterfaceWrapper) GetFeed(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFeed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/1/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/1/auth/logout", wrapper.LogoutUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/1/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/1/tweets/create_post", wrapper.CreateTweet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/1/tweets/feed", wrapper.GetFeed)
	})

	return r
}

type AuthResponseJSONResponse struct {
	AccessToken string `json:"accessToken"`
}

type BadRequestJSONResponse struct {
	Error string `json:"error"`
}

type InternalErrorJSONResponse struct {
	Error string `json:"error"`
}

type NotFoundErrorJSONResponse struct {
	Error string `json:"error"`
}

type UnauthorizedResponse struct {
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse struct{ AuthResponseJSONResponse }

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401Response struct {
}

func (response LoginUser401Response) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LoginUser404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response LoginUser404JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500JSONResponse struct{ InternalErrorJSONResponse }

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutUserRequestObject struct {
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser204Response struct {
}

func (response LogoutUser204Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LogoutUser401Response = UnauthorizedResponse

func (response LogoutUser401Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type LogoutUser500JSONResponse struct{ InternalErrorJSONResponse }

func (response LogoutUser500JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse struct{ AuthResponseJSONResponse }

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409Response struct {
}

func (response RegisterUser409Response) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type RegisterUser500JSONResponse struct{ InternalErrorJSONResponse }

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTweetRequestObject struct {
	Body *CreateTweetJSONRequestBody
}

type CreateTweetResponseObject interface {
	VisitCreateTweetResponse(w http.ResponseWriter) error
}

type CreateTweet201JSONResponse Tweet

func (response CreateTweet201JSONResponse) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTweet400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTweet400JSONResponse) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTweet401Response = UnauthorizedResponse

func (response CreateTweet401Response) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateTweet500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTweet500JSONResponse) VisitCreateTweetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFeedRequestObject struct {
}

type GetFeedResponseObject interface {
	VisitGetFeedResponse(w http.ResponseWriter) error
}

type GetFeed200JSONResponse []Tweet

func (response GetFeed200JSONResponse) VisitGetFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFeed500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetFeed500JSONResponse) VisitGetFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Вход
	// (POST /api/1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Выход
	// (POST /api/1/auth/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// Регистрация нового пользователя
	// (POST /api/1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Создать новый пост
	// (POST /api/1/tweets/create_post)
	CreateTweet(ctx context.Context, request CreateTweetRequestObject) (CreateTweetResponseObject, error)
	// Получить ленту постов
	// (GET /api/1/tweets/feed)
	GetFeed(ctx context.Context, request GetFeedRequestObject) (GetFeedResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(w http.ResponseWriter, r *http.Request) {
	var request LogoutUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx, request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		if err := validResponse.VisitLogoutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTweet operation middleware
func (sh *strictHandler) CreateTweet(w http.ResponseWriter, r *http.Request) {
	var request CreateTweetRequestObject

	var body CreateTweetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTweet(ctx, request.(CreateTweetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTweet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTweetResponseObject); ok {
		if err := validResponse.VisitCreateTweetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFeed operation middleware
func (sh *strictHandler) GetFeed(w http.ResponseWriter, r *http.Request) {
	var request GetFeedRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFeed(ctx, request.(GetFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFeed")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFeedResponseObject); ok {
		if err := validResponse.VisitGetFeedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXX2sbRxD/Kse2DwlcfVKjlPTe7JAElxBM4tAHY8r6bixtrLu97O0ldo3Alug/HDDk",
	"tZQ09AuorlWrMZK/wuw3KrsrWSfpFMlJTfMi7m53Z34z89v5jfZJwKOExxDLlPj7RECa8DgF87Kcydrj",
	"wQf9HvBYQiz1I02SOguoZDz2nqU81t/SoAYR1U+J4AkIyawZGgSQput8B8w2uZcA8UkqBYurpNFwiYDn",
	"GRMQEn9jbPOmO9zMt55BIElD7w4hDQRLtGviE/xDHeIFdtTP2MO2OnbUAXbwL+yqQ9VUB9hWP2JXHZOG",
	"S1Zo+BieZ5DKjwgGhOBifhh22yIBrNDQERaWc6NSKt3UUFdjCSKm9XtDb58K2iEwxyBzbtweAH7E5X2e",
	"xeEnB/gRl45BNkRcKVUM4qcxzWSNC/a9Nrk/cSy/qs+UbxoMFrZB+pBXWZzj03gcCU3Tl1wYyxGLH0Jc",
	"lTXil93JwFySpTqjEczdOpGDy3PuyNt0RlzyGKoslSBmYl3IuTsrpK8WD6kyL6RBOItGtv4SoCCeQACV",
	"EC6bpW0uIiqJT0Iq4QvJjNUpwCzMcY7FEqog9HcJu/KqdWEhGRx0c1Bm4r9rtkxH8SGuzZmCW+GSFIJM",
	"MLn3RBPYOlgBKkDoHq/ftszb/WG2vvl2nQzori3Z1VHmalIm9raxeJsP7zsN5IhP5F6dxdS5W2PxDoup",
	"LquoD46mvudVmaxlW0sBj7ydLBQR3SVTl3d5bdXBUzxXx84aiG0IpLMG0lkT3ATmEslkXfsqWHWW11aJ",
	"S16ASK2x0lJ5qaR98ARimjDik1tLpaVbhmWyZnLi0YR5ZU/ffa+uL7ipC7e3RlfHdLHVkPj2/j9NTVYG",
	"/XuFh3tX6n2fC9gmPvnMG4mwN2gx3lh/aYxXWooMzIecWH9ZKs0yebnPG1P0hksqpfJ078PfsIMn2FEH",
	"2FNH+I+D59jXkoo9B7t4jl0HL7CtDrCP5+qVtVOZ73xcIxouub0I5HEpzHOZ+BubLkmzKKJiT+N+rX7A",
	"Pp6aTROV5Jl8byl5Ji9rOZbUSkF+Xqsj68nBE3WEFzoP2MMO9hzVyo0j/VyK3x/kmBh9RGbyuTiakQ0x",
	"0IPZ+RgqxjWye1KUFiJ4+UMI/nVBAd9Y5uIZ9vEE26qJHf3uqBb+jR1HHaqW+gU7eoTEE9XCjmpeB19/",
	"L5pUHU0cPDE3ru9Yck1BPc5XVWoZST2rNd8NS1pcWqs2VjivWlnYpVFSt8XYokYxR8Hkx9gtbc8lL2g9",
	"g5GUEYO5yvnEyQeczz36hEfgmOfGaAybx7G8vC7Or/+E3jbBRX9X3mBf19tRh9jHMzzFNvYsURfgVu4f",
	"zP/XWd4OgaumejVgq5WJCxtbATe3wQ7ZVSjg5AOQ9/V6saAtXA8mIUoXLMzlIEOFoHuFhXqLF/pqYh/f",
	"XUamQ72ORmD7UUv9hF2b1HMtJqqpWhOuJ6yMD3Ebmw1tFoSeeczqREi/6mCwbfqJVXZ1aGTeiP1w0tKt",
	"CM/M75/YV018h92x6c33vDoPaL3GU+nfKd0pkcZm498AAAD//xRYUeVJEAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
