openapi: 3.0.3

info:
  title: Perfect Pet Project API
  version: "0.1.0"
  description: "API для Perfect Pet Project"
  contact:
    name: "Elina Chinkina"
    url: "https://github.com/kudrmax"

servers:
  - url: http://localhost:8080
    description: "Локальный сервер для разработки"

paths:
  /api/1/posts/create_post:
    $ref: 'paths/posts/create.yaml'
  /api/1/posts/feed:
    $ref: 'paths/posts/feed.yaml'