openapi: 3.0.3

info:
  title: Perfect Pet Project API
  version: "0.1.0"
  description: "API для Perfect Pet Project"
  contact:
    name: "Elina Chinkina"
    url: "https://github.com/kudrmax"

servers:
  - url: http://localhost:8080
    description: "Локальный сервер для разработки"

security:
  - BearerAuth: []

paths:
  /api/1/auth/register:
    $ref: 'paths/auth/register.yaml'
  /api/1/auth/login:
    $ref: 'paths/auth/login.yaml'
  /api/1/tweets/create_post:
    $ref: 'paths/tweets/create.yaml'
  /api/1/tweets/feed:
    $ref: 'paths/tweets/feed.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT